name: Continuous Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: yarn --no-progress --non-interactive --frozen-lockfile

      - name: Test
        run: yarn test --colors --coverage

      - name: Lint
        run: yarn lint

      - name: Build service worker
        run: yarn build:sw
